from __future__ import annotations

from copy import deepcopy
from datetime import UTC, date, datetime, timedelta
from typing import Any

SAMPLE_REPOSITORIES: list[dict[str, Any]] = [
    {
        "id": 1001,
        "full_name": "vllm-project/vllm",
        "description": "A high-throughput and memory-efficient inference engine for LLMs.",
        "language": "Python",
        "topics": ["llm", "inference", "serving"],
        "license": {"spdx_id": "Apache-2.0"},
        "stars": 42000,
        "forks": 6800,
        "watchers": 520,
        "open_issues": 980,
        "stars_delta_7d": 1250,
        "forks_delta_7d": 260,
        "watchers_delta_7d": 42,
        "commits_7d": 86,
        "prs_opened_7d": 43,
        "prs_merged_7d": 31,
        "issues_opened_7d": 72,
        "issues_closed_7d": 55,
        "contributor_count": 640,
        "release_days_ago": 8,
    },
    {
        "id": 1002,
        "full_name": "langchain-ai/langchain",
        "description": "Build context-aware reasoning applications with LLMs.",
        "language": "Python",
        "topics": ["llm", "rag", "agents"],
        "license": {"spdx_id": "MIT"},
        "stars": 99000,
        "forks": 17000,
        "watchers": 1100,
        "open_issues": 2100,
        "stars_delta_7d": 1020,
        "forks_delta_7d": 185,
        "watchers_delta_7d": 35,
        "commits_7d": 112,
        "prs_opened_7d": 65,
        "prs_merged_7d": 44,
        "issues_opened_7d": 95,
        "issues_closed_7d": 74,
        "contributor_count": 2100,
        "release_days_ago": 3,
    },
    {
        "id": 1003,
        "full_name": "ollama/ollama",
        "description": "Run large language models locally.",
        "language": "Go",
        "topics": ["llm", "local-ai", "inference"],
        "license": {"spdx_id": "MIT"},
        "stars": 128000,
        "forks": 10400,
        "watchers": 920,
        "open_issues": 1500,
        "stars_delta_7d": 1680,
        "forks_delta_7d": 210,
        "watchers_delta_7d": 52,
        "commits_7d": 52,
        "prs_opened_7d": 27,
        "prs_merged_7d": 16,
        "issues_opened_7d": 88,
        "issues_closed_7d": 46,
        "contributor_count": 730,
        "release_days_ago": 5,
    },
    {
        "id": 1004,
        "full_name": "huggingface/transformers",
        "description": "State-of-the-art machine learning for PyTorch, TensorFlow, and JAX.",
        "language": "Python",
        "topics": ["machine-learning", "transformer", "nlp"],
        "license": {"spdx_id": "Apache-2.0"},
        "stars": 142000,
        "forks": 28000,
        "watchers": 1600,
        "open_issues": 1700,
        "stars_delta_7d": 760,
        "forks_delta_7d": 150,
        "watchers_delta_7d": 20,
        "commits_7d": 95,
        "prs_opened_7d": 51,
        "prs_merged_7d": 38,
        "issues_opened_7d": 64,
        "issues_closed_7d": 60,
        "contributor_count": 2900,
        "release_days_ago": 10,
    },
    {
        "id": 1005,
        "full_name": "microsoft/autogen",
        "description": "A programming framework for agentic AI.",
        "language": "Python",
        "topics": ["ai-agent", "llm", "multi-agent"],
        "license": {"spdx_id": "MIT"},
        "stars": 47000,
        "forks": 7000,
        "watchers": 480,
        "open_issues": 620,
        "stars_delta_7d": 890,
        "forks_delta_7d": 130,
        "watchers_delta_7d": 25,
        "commits_7d": 64,
        "prs_opened_7d": 30,
        "prs_merged_7d": 21,
        "issues_opened_7d": 42,
        "issues_closed_7d": 31,
        "contributor_count": 520,
        "release_days_ago": 19,
    },
    {
        "id": 1006,
        "full_name": "run-llama/llama_index",
        "description": "Data framework for LLM applications and retrieval augmented generation.",
        "language": "Python",
        "topics": ["llm", "rag", "data-framework"],
        "license": {"spdx_id": "MIT"},
        "stars": 39000,
        "forks": 5400,
        "watchers": 390,
        "open_issues": 760,
        "stars_delta_7d": 720,
        "forks_delta_7d": 95,
        "watchers_delta_7d": 18,
        "commits_7d": 78,
        "prs_opened_7d": 39,
        "prs_merged_7d": 26,
        "issues_opened_7d": 50,
        "issues_closed_7d": 44,
        "contributor_count": 900,
        "release_days_ago": 4,
    },
    {
        "id": 1007,
        "full_name": "openai/openai-cookbook",
        "description": "Examples and guides for building with OpenAI models.",
        "language": "Jupyter Notebook",
        "topics": ["llm", "generative-ai", "examples"],
        "license": {"spdx_id": "MIT"},
        "stars": 69000,
        "forks": 11000,
        "watchers": 760,
        "open_issues": 420,
        "stars_delta_7d": 640,
        "forks_delta_7d": 110,
        "watchers_delta_7d": 21,
        "commits_7d": 34,
        "prs_opened_7d": 18,
        "prs_merged_7d": 9,
        "issues_opened_7d": 35,
        "issues_closed_7d": 20,
        "contributor_count": 450,
        "release_days_ago": 120,
    },
    {
        "id": 1008,
        "full_name": "microsoft/semantic-kernel",
        "description": "SDK that integrates AI services with conventional programming languages.",
        "language": "C#",
        "topics": ["llm", "agents", "semantic-kernel"],
        "license": {"spdx_id": "MIT"},
        "stars": 26000,
        "forks": 3600,
        "watchers": 300,
        "open_issues": 540,
        "stars_delta_7d": 510,
        "forks_delta_7d": 80,
        "watchers_delta_7d": 14,
        "commits_7d": 72,
        "prs_opened_7d": 33,
        "prs_merged_7d": 24,
        "issues_opened_7d": 37,
        "issues_closed_7d": 40,
        "contributor_count": 610,
        "release_days_ago": 6,
    },
    {
        "id": 1009,
        "full_name": "crewAIInc/crewAI",
        "description": "Framework for orchestrating role-playing autonomous AI agents.",
        "language": "Python",
        "topics": ["ai-agent", "agents", "llm"],
        "license": {"spdx_id": "MIT"},
        "stars": 33000,
        "forks": 4200,
        "watchers": 350,
        "open_issues": 690,
        "stars_delta_7d": 930,
        "forks_delta_7d": 140,
        "watchers_delta_7d": 30,
        "commits_7d": 48,
        "prs_opened_7d": 25,
        "prs_merged_7d": 17,
        "issues_opened_7d": 58,
        "issues_closed_7d": 33,
        "contributor_count": 360,
        "release_days_ago": 11,
    },
    {
        "id": 1010,
        "full_name": "QwenLM/Qwen",
        "description": "Large language model and multimodal model family.",
        "language": "Python",
        "topics": ["llm", "generative-ai", "multimodal"],
        "license": {"spdx_id": "Apache-2.0"},
        "stars": 28000,
        "forks": 2200,
        "watchers": 280,
        "open_issues": 310,
        "stars_delta_7d": 1180,
        "forks_delta_7d": 125,
        "watchers_delta_7d": 33,
        "commits_7d": 41,
        "prs_opened_7d": 15,
        "prs_merged_7d": 11,
        "issues_opened_7d": 29,
        "issues_closed_7d": 20,
        "contributor_count": 290,
        "release_days_ago": 14,
    },
    {
        "id": 1011,
        "full_name": "microsoft/DeepSpeed",
        "description": "Deep learning optimization library for distributed training and inference.",
        "language": "Python",
        "topics": ["deep-learning", "training", "inference"],
        "license": {"spdx_id": "MIT"},
        "stars": 37000,
        "forks": 4600,
        "watchers": 410,
        "open_issues": 980,
        "stars_delta_7d": 420,
        "forks_delta_7d": 74,
        "watchers_delta_7d": 10,
        "commits_7d": 61,
        "prs_opened_7d": 28,
        "prs_merged_7d": 19,
        "issues_opened_7d": 35,
        "issues_closed_7d": 32,
        "contributor_count": 830,
        "release_days_ago": 24,
    },
    {
        "id": 1012,
        "full_name": "chromadb/chroma",
        "description": "The AI-native open-source embedding database.",
        "language": "Python",
        "topics": ["vector-database", "embedding", "rag"],
        "license": {"spdx_id": "Apache-2.0"},
        "stars": 21000,
        "forks": 1700,
        "watchers": 220,
        "open_issues": 430,
        "stars_delta_7d": 380,
        "forks_delta_7d": 56,
        "watchers_delta_7d": 9,
        "commits_7d": 39,
        "prs_opened_7d": 17,
        "prs_merged_7d": 12,
        "issues_opened_7d": 25,
        "issues_closed_7d": 21,
        "contributor_count": 330,
        "release_days_ago": 16,
    },
]


def make_sample_repositories(week_start: date) -> list[dict[str, Any]]:
    start_dt = datetime.combine(week_start, datetime.min.time(), tzinfo=UTC)
    repos: list[dict[str, Any]] = []
    for index, item in enumerate(SAMPLE_REPOSITORIES):
        repo = deepcopy(item)
        owner, name = repo["full_name"].split("/", 1)
        repo["name"] = name
        repo["owner"] = {"login": owner}
        repo["html_url"] = f"https://github.com/{repo['full_name']}"
        repo["stargazers_count"] = repo["stars"]
        repo["forks_count"] = repo["forks"]
        repo["watchers_count"] = repo["watchers"]
        repo["open_issues_count"] = repo["open_issues"]
        repo["default_branch"] = "main"
        repo["fork"] = False
        repo["archived"] = False
        repo["has_readme"] = True
        repo["created_at"] = (start_dt - timedelta(days=900 + index * 47)).isoformat().replace("+00:00", "Z")
        repo["pushed_at"] = (start_dt + timedelta(days=6, hours=10 - index % 5)).isoformat().replace("+00:00", "Z")
        release_days_ago = int(repo.pop("release_days_ago"))
        repo["latest_release_at"] = (
            start_dt + timedelta(days=6) - timedelta(days=release_days_ago)
        ).isoformat().replace("+00:00", "Z")
        repo["release_count"] = 12 + index
        repos.append(repo)
    return repos

